<?php
/**
 * Basic theme setup.
 *
 * @package ECOVARO_Starter
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}

if ( ! function_exists( 'ECOVARO_setup' ) ) :
	/**
	 * Sets up theme defaults and registers support for various WordPress features.
	 */
	function ECOVARO_setup() {
		// Set the text domain for translations.
		load_theme_textdomain( 'ecovaro', get_template_directory() . '/languages' );

		// Add default posts and comments RSS feed links to head.
		add_theme_support( 'automatic-feed-links' );

		// Let WordPress manage the document title.
		add_theme_support( 'title-tag' );

		// Enable support for Post Thumbnails on posts and pages.
		add_theme_support( 'post-thumbnails' );

		// This theme uses wp_nav_menu() in one location.
		register_nav_menus(
			array(
				'primary_menu' => esc_html__( 'Primary Menu', 'ecovaro' ),
				// 'footer_menu'  => esc_html__( 'Footer Menu (general)', 'ecovaro' ),
				'footer1'      => esc_html__( 'Footer - column 1', 'ecovaro' ),
				'footer2'      => esc_html__( 'Footer - column 2', 'ecovaro' ),
			)
		);

		// Switch default core markup for search form, comment form, and comments to output valid HTML5.
		add_theme_support(
			'html5',
			array(
				'search-form',
				'comment-form',
				'comment-list',
				'gallery',
				'caption',
				'style',
				'script',
			)
		);

		// Enable support for custom logo.
		add_theme_support(
			'custom-logo',
			array(
				'height'      => 100,
				'width'       => 300,
				'flex-height' => true,
				'flex-width'  => true,
			)
		);

		// Add theme support for selective refresh for widgets.
		add_theme_support( 'wp-block-styles' );

		// Add support for wide-aligned images.
		add_theme_support( 'align-wide' );

		// Hide the admin bar on the front end.
		add_filter( 'show_admin_bar', '__return_false' );
	}
endif;
add_action( 'after_setup_theme', 'ECOVARO_setup' );



// Contact_Form_7  //

/**
 * Removes <p> and <span> tags automatically generated by Contact Form 7.
 * This allows full control over the form's HTML structure.
 */
add_filter('wpcf7_autop_or_not', '__return_false');

add_filter('wpcf7_form_elements', function($content) {
    // Enables the use of shortcodes (e.g., [theme_uri]) inside the CF7 form.
    return do_shortcode( $content );
});


/**
 * Dynamically sets the default value for a field in Contact Form 7.
 * Used to pass the job offer title to the application form.
 */
function ECOVARO_cf7_dynamic_job_title( $tag ) {
    if ( 'job-offer-title' !== $tag['name'] ) {
        return $tag;
    }

    if ( isset( $_GET['offer_id'] ) ) {
        $offer_id = absint( $_GET['offer_id'] );
        $offer_title = get_the_title( $offer_id );

        if ( $offer_title ) {
            $tag['values'] = array( $offer_title );
        }
    }

    return $tag;
}
add_filter( 'wpcf7_form_tag', 'ECOVARO_cf7_dynamic_job_title', 10, 1 );

/**
 * Creates a [theme_uri] shortcode that returns the path to the active theme directory.
 * Useful for inserting images or other resources in content, e.g., in Contact Form 7.
 * @return string URL to the theme directory.
 */
function ECOVARO_theme_uri_shortcode() {
	return get_template_directory_uri();
}
add_shortcode( 'theme_uri', 'ECOVARO_theme_uri_shortcode' );

// Contact_Form_7  END //



/**
 * Secures the "Apply" page so it is only accessible with a valid job offer ID.
 * Redirects to the homepage if someone tries to access it directly
 * or with an invalid parameter.
 */
function ECOVARO_restrict_apply_page_access() {

    // Slug of the Apply page in the default language
    $base_slug = 'aplikuj';

    // Get the page by path in the default language
    $base_page = get_page_by_path( $base_slug, OBJECT, 'page' );

    if ( ! $base_page ) {
        return; // page does not exist
    }


    // Check if we are on the Apply page
    if ( ! is_page( $base_page ) ) {
        return; // we are not on the apply page -> do nothing
    }

    // Admins always have access
    if ( current_user_can( 'manage_options' ) ) {
        return;
    }

    // Check the offer_id parameter
    if ( empty( $_GET['offer_id'] ) ) {
        wp_redirect( home_url() );
        exit;
    }

    $offer_id = absint( $_GET['offer_id'] );

    // Check if the provided ID is actually a job offer
    if ( get_post_type( $offer_id ) !== 'job_offer' ) {
        wp_redirect( home_url() );
        exit;
    }
}
add_action( 'template_redirect', 'ECOVARO_restrict_apply_page_access' );



function ECOVARO_register_cpt_job_offer() {

    $labels = array(
        'name'               => __('Oferty Pracy', 'ecovaro'),
        'singular_name'      => __('Oferta Pracy', 'ecovaro'),
        'menu_name'          => __('Oferty Pracy', 'ecovaro'),
        'name_admin_bar'     => __('Oferta Pracy', 'ecovaro'),
        'add_new'            => __('Dodaj nową', 'ecovaro'),
        'add_new_item'       => __('Dodaj nową ofertę pracy', 'ecovaro'),
        'new_item'           => __('Nowa oferta pracy', 'ecovaro'),
        'edit_item'          => __('Edytuj ofertę pracy', 'ecovaro'),
        'view_item'          => __('Zobacz ofertę pracy', 'ecovaro'),
        'all_items'          => __('Wszystkie oferty pracy', 'ecovaro'),
        'search_items'       => __('Szukaj ofert pracy', 'ecovaro'),
        'parent_item_colon'  => __('Nadrzędna oferta pracy:', 'ecovaro'),
        'not_found'          => __('Nie znaleziono ofert pracy.', 'ecovaro'),
        'not_found_in_trash' => __('Brak ofert pracy w koszu.', 'ecovaro'),
    );

    $args = array(
        'labels'             => $labels,
        'public'             => true,
        'has_archive'        => true,
        'rewrite'            => array('slug' => 'oferty-pracy', 'with_front' => false),
        'show_in_rest'       => true,
        'supports'           => array('title', 'editor', 'thumbnail', 'excerpt', 'revisions'),
        'menu_position'      => 6,
        'menu_icon'          => 'dashicons-businessman',
        'show_in_menu'       => true,
        'show_in_admin_bar'  => true,
        'publicly_queryable' => true,
        'exclude_from_search'=> false,
        'capability_type'    => 'post',
    );

    register_post_type('job_offer', $args);
}
add_action('init', 'ECOVARO_register_cpt_job_offer');


/**
 * Disable Gutenberg (block) editor for pages.
 * Restores the classic editing appearance, which works better with Carbon Fields.
 */
function ECOVARO_disable_gutenberg( $use_block_editor, $post ) {
    // If we are editing a page ('page') or job offers, disable Gutenberg
    if ( $post && ( 'page' === $post->post_type || 'job_offer' === $post->post_type ) ) {
        return false;
    }
    return $use_block_editor;
}
add_filter( 'use_block_editor_for_post', 'ECOVARO_disable_gutenberg', 10, 2 );

/**
 * Hide the main content editor (WYSIWYG) for pages.
 * Equivalent to the "Hide Content Editor" option in ACF.
 * This ensures the editor only sees the Title and Carbon Fields.
 */
function ECOVARO_remove_content_editor() {
    remove_post_type_support( 'page', 'editor' );
}
add_action( 'admin_init', 'ECOVARO_remove_content_editor' );

/**
 * Disable support for comments, trackbacks, and native custom fields
 * for all post types. This cleans up the editing interface.
 */
function ECOVARO_disable_post_type_features() {
    $post_types = get_post_types();

    foreach ( $post_types as $post_type ) {
        // Disable comments
        if ( post_type_supports( $post_type, 'comments' ) ) {
            remove_post_type_support( $post_type, 'comments' );
        }
        // Disable trackbacks (discussions)
        if ( post_type_supports( $post_type, 'trackbacks' ) ) {
            remove_post_type_support( $post_type, 'trackbacks' );
        }
        // Disable standard "Custom Fields" metabox (unnecessary with Carbon Fields/ACF)
        if ( post_type_supports( $post_type, 'custom-fields' ) ) {
            remove_post_type_support( $post_type, 'custom-fields' );
        }
    }
}
add_action( 'admin_init', 'ECOVARO_disable_post_type_features' );

/**
 * Remove "Comments" menu from the admin panel and toolbar.
 */
function ECOVARO_remove_comments_menu() {
    // Remove from the left menu
    remove_menu_page( 'edit-comments.php' );
}
add_action( 'admin_menu', 'ECOVARO_remove_comments_menu' );

function ECOVARO_remove_comments_admin_bar() {
    // Remove from the top admin bar
    global $wp_admin_bar;
    $wp_admin_bar->remove_menu( 'comments' );
}
add_action( 'wp_before_admin_bar_render', 'ECOVARO_remove_comments_admin_bar' );


// Orphans setup

function cf_the_content( $value ) {
    if ( empty( $value ) ) {
        return '';
    }

    $value = apply_filters( 'orphan_replace', $value );
    $value = wpautop( $value );

    return $value;
}

function cf_text( $value ) {
    if ( empty( $value ) ) {
        return '';
    }

    $value = apply_filters( 'orphan_replace', $value );

    return wp_kses_post( $value );
}

function cf_the_content_br( $value ) {
    if ( empty( $value ) ) {
        return '';
    }

    $value = apply_filters( 'orphan_replace', $value );
    $value = nl2br( esc_html( $value ) );

    return $value;
}


function add_custom_iworks_orphan_terms( $terms ) {

    $custom_terms = array(
        'się',
        'dla',
        'ich'
    );

    return array_unique( array_merge( $terms, $custom_terms ) );
}

add_filter( 'iworks_orphan_terms', 'add_custom_iworks_orphan_terms' );

?>